@baseUrl = https://thesis.cyclic.app

### GET ALL
GET {{baseUrl}}/customers



### GET ONE
GET {{baseUrl}}/customers/1



### CREATE/UPDATE
POST {{baseUrl}}/customers/1
Content-Type: application/json

{
    "cust_username":"farrah",
    "cust_password": "farrah123",
    "cust_name": "Farrah Zakir",
    "cust_phone": "+12345",
    "cust_address": "Bamberg"
}



### DELETE
DELETE {{baseUrl}}/customers/1